platform :ios, '12.0'

target 'Currency-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Currency-app
    use_frameworks!
    pod 'Kanna', '~> 5.2.2'
  
end
